config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :chatrooms
  root "firstpages#index"
  resources :forums
  resources :users, only: [:index, :create]
  resources :sessions, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :create, :new]
  scope '/homes' do
    resources :profiles, only: [:index, :create]
  end
  get '/forumsearch', to: "forums#search", as: 'search_forum'
  resources :firstpages
  resources :chatrooms do
    resources :chatroom_users
    resources :messages
    resources :chatroomposts
  end

  post '/createintro/:id', to: "homes#createupdateintro", as: "create_intro"

  

end

app/models/chatroompost.rb
class Chatroompost < ApplicationRecord
	belongs_to :chatroom

	def self.find_post_author_img(post)
		User.find_by_username(post.author).image_url(:thumb)
	end
end

app/controllers/chatroomposts_controller.rb
class ChatroompostsController < ApplicationController
  before_action :set_chatroompost, only: [:show, :edit, :update, :destroy]
  before_action :set_chatroom

  # GET /chatroomposts
  # GET /chatroomposts.json
  def index
    @chatroompost = @chatroom.chatroomposts.new
    @chatroomposts = @chatroom.chatroomposts.all
  end

  # GET /chatroomposts/1
  # GET /chatroomposts/1.json
  def show
  end

  # GET /chatroomposts/new
  def new
    @chatroompost = Chatroompost.new
  end

  # GET /chatroomposts/1/edit
  def edit
  end

  # POST /chatroomposts
  # POST /chatroomposts.json
  def create
    @chatroompost = @chatroom.chatroomposts.new(chatroompost_params)
    respond_to do |format|
      if @chatroompost.save
        format.html { redirect_to chatroom_chatroomposts_path(@chatroom), notice: 'Chatroompost was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /chatroomposts/1
  # PATCH/PUT /chatroomposts/1.json
  def update
    respond_to do |format|
      if @chatroompost.update(chatroompost_params)
        format.html { redirect_to @chatroompost, notice: 'Chatroompost was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroompost }
      else
        format.html { render :edit }
        format.json { render json: @chatroompost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatroomposts/1
  # DELETE /chatroomposts/1.json
  def destroy
    @chatroompost.destroy
    respond_to do |format|
      format.html { redirect_to chatroomposts_url, notice: 'Chatroompost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroompost
      @chatroompost = Chatroompost.find(params[:chatroompost_id])
    end

    def set_chatroom
      @chatroom = Chatroom.find(params[:chatroom_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroompost_params
      params.require(:chatroompost).permit(:content, :author)
    end
end

app/helpers/chatroomposts_helper.rb
module ChatroompostsHelper
end

app/views/chatroomposts/_form.html.haml
= form_for chatroompost, url: chatroom_chatroomposts_path(@chatroom,chatroompost) do |f|
  = f.label :content
  = f.text_field :content
  = f.submit

app/views/chatroomposts/edit.html.erb
<h1>Editing Chatroompost</h1>

<%= render 'form', chatroompost: @chatroompost %>

<%= link_to 'Show', @chatroompost %> |
<%= link_to 'Back', chatroomposts_path %>

app/views/chatroomposts/index.html.haml
#form_div
  #form_div_description
    Share something interesting!
  #form_container
    = form_for @chatroompost, url: chatroom_chatroomposts_path(@chatroom,@chatroompost) do |f|
      = f.text_area :content
      = f.hidden_field :author, :value => current_user.username
      = f.submit
      = label_tag "upload", nil, class: "custom-file-upload"
      = f.file_field :content, :id => "file-upload"

- @chatroomposts.each do |chatroompost|
  #each_group_post
    #photo_container
      <!-- = image_tag src = Chatroompost.find_post_author_img(chatroompost), :id => "selfie" -->
      = image_tag src = "http://gurucul.com/wp-content/uploads/2015/01/default-user-icon-profile.png", :id => "selfie"
    #author_container
      = chatroompost.author
    #post_container
      = chatroompost.content
    #appraisal_container
      %i.fa.fa-thumbs-up
    #reply

app/views/chatroomposts/new.html.haml
%h1 New Chatroompost
= render 'form', chatroompost: @chatroompost
= link_to 'Back', chatroom_chatroomposts_path

app/views/chatroomposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @chatroompost.author %>
</p>

<%= link_to 'Edit', edit_chatroompost_path(@chatroompost) %> |
<%= link_to 'Back', chatroomposts_path %>