config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :chatrooms
  root "firstpages#index"
  resources :forums
  resources :users, only: [:index, :create]
  resources :sessions, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :create, :new]
  scope '/homes' do
    resources :profiles, only: [:index, :create]
  end
  get '/forumsearch', to: "forums#search", as: 'search_forum'
  resources :firstpages
  resources :chatrooms do
    resources :chatroom_users
    resources :messages
    resources :chatroomposts
  end

  post '/createintro/:id', to: "homes#createupdateintro", as: "create_intro"

  

end

app/models/forum.rb
class Forum < ApplicationRecord
    def self.filter_by_college_name(arg)
      record = Forum.where('name LIKE ?', '%'+ arg.strip+ '%').all
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :find_forum, only: [:show, :destroy]
    
    def create
        @forum = Forum.new(forum_params)
        if @forum.save
            redirect_to forum_path(@forum.id)
        else
            render "create"
        end
    end
    
    def index
        @user = current_user
        @forum = Forum.new
        respond_to do |format|
            format.html
        end
    end
    
    def search
        @user = current_user
        if params[:content]
          puts "params is"
          puts params[:content]
          @course = Forum.filter_by_college_name(params[:content])
          puts "hehehehe"
          puts @course
          respond_to do |format|
            format.html
            format.json {render json: @course}
          end
        end
    end
    
    def show
        @name = @forum.name
        @coursename = @forum.coursename
    end
    
    def destroy
    
    end
    
    private
    def forum_params
        params.require(:forum).permit(:name, :coursename)
    end
    
    def find_forum
        @forum = Forum.find(params[:id])
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
    
end

app/views/forums/index.html.haml
= render "homes/navigation"
#content-container
  = form_for @forum, :url => forums_path(@forum), :method => :post do |f|
    = f.label "Create a New School"
    = f.text_field :name
    = f.label "Create a New Course"
    = f.text_field :coursename
    = f.submit "Create the course"

app/views/forums/search.html.haml
= render "homes/navigation"
= form_tag(search_forum_path, :method => "get") do
  = label_tag :school, "Search the school"
  = text_field_tag :school, nil, :id => "school-input"
#content-container

app/views/forums/show.html.haml
%p
  Welcome to the course
  = @coursename 
  from 
  = @name