config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :chatrooms
  root "firstpages#index"
  resources :forums
  resources :users, only: [:index, :create]
  resources :sessions, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :create, :new]
  scope '/homes' do
    resources :profiles, only: [:index, :create]
  end
  get '/forumsearch', to: "forums#search", as: 'search_forum'
  resources :firstpages
  resources :chatrooms do
    resources :chatroom_users
    resources :messages
    resources :chatroomposts
  end

  post '/createintro/:id', to: "homes#createupdateintro", as: "create_intro"

  

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
	has_many :chatroomposts
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.js
  def index
    @chatrooms = Chatroom.all
    session[:category] ||= ""
    session[:size] ||= ""
    session[:position] ||= ""
    if session[:category] != params[:category]
      session[:category] = session[:category] + params[:category] + "%" if !params[:category].nil? and !session[:category].split("%").include?(params[:category])
    end
    if session[:size] != params[:size]
      session[:size] = session[:size] + params[:size] + "%" if !params[:size].nil? and !session[:size].split("%").include?(params[:size])
    end
    if session[:position] != params[:position]
      session[:position] = session[:position] + params[:position] + "%" if !params[:position].nil? and !session[:position].split("%").include?(params[:position])
    end
    category = session[:category].split("%")
    size = session[:size].split("%")
    position = session[:position].split("%")
    @chatrooms = @chatrooms.where(category: category) if !session[:category].empty?
    @chatrooms = @chatrooms.where(size: size) if !session[:size].empty?
    @chatrooms = @chatrooms.where(position: position) if !session[:position].empty?
    if session[:position] != params[:position] || session[:size] != params[:size] || session[:category] != params[:category]
      return redirect_to :category => session[:category] , :size => session[:size], :position => session[:position]
    end
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
    respond_to do |format|
      format.html {}
    end
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        @chatroom.chatroom_users.where(:user_id => current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:name, :size, :category, :visibility, :position)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_filter.html.erb
<div id = "chatroom-filter">
	<div id = "all-filter"><div>
	<ul id="drop-nav">
		<div></div>
  		<li><a href="#">Group Topic</a>
    		<ul>
      			<li>
      				<%= link_to 'Sports', chatrooms_path(:category =>  "Sports") %>
      			</li>
      			<li>
      				<%= link_to 'Music', chatrooms_path(:category => "Music") %>
      			</li>
      			<li>
      				<%= link_to 'Entertainment', chatrooms_path(:category => "Entertainment") %>
      			</li>
      			<li>
      				<%= link_to 'NBA', chatrooms_path(:category => "NBA") %>
      			</li>
    		</ul>
  		</li>
  		<li><a href="#">Group Size</a>
    		<ul>
      			<li>
      				<%= link_to '1-5 persons', chatrooms_path(:size =>  "1-5 persons") %>
      			</li>
      			<li>
      				<%= link_to '6-10 persons', chatrooms_path(:size =>  "6-10 persons") %>
      			</li>
      			<li>
      				<%= link_to '11-50 persons', chatrooms_path(:size =>  "11-50 persons") %>
      			</li>
      			<li>
      				<%= link_to '50-100 persons', chatrooms_path(:size =>  "50-100 persons") %>
      			</li>
      			<li>
      				<%= link_to '100-200 persons', chatrooms_path(:size =>  "100-200 persons") %>
      			</li>
      			<li>
      				<%= link_to 'More than 200 persons', chatrooms_path(:size =>  "More than 200 persons") %>
      			</li>
    		</ul>
  		</li>
  		<li><a href="#">Group Meet Position</a>
    		<ul>
    			<li>
      				<%= link_to 'Beijing', chatrooms_path(:position =>  "Beijing") %>
      			</li>
      			<li>
      				<%= link_to 'Shanghai', chatrooms_path(:position =>  "Shanghai") %>
      			</li>
    		</ul>
  		</li>
	</ul>
	<div class = "showchatroom">
		<h1 class = "chatroomheader">All Groups</h1>
		<% @chatrooms.each do |chatroom| %>
			<p>
				<%= link_to chatroom.name, chatroom_chatroom_users_path(chatroom), :method => :post, :id => chatroom.id%>
				<span class = "tailspan"><%= chatroom.users.length %> users chatting in this room</span>
			</p>
		<% end %>
	</div>

</div>

app/views/chatrooms/_form.html.erb
<div class = "chatroom-form-container">
  <h1>Create Your Own Group</h1>
  <%= form_for(@chatroom) do |f| %>
    <div class="field">
      <div><%= f.label :name, 'Group Name:' %><%= f.text_field :name %></div>
      <div><%= f.label :position, 'Group Meet Position:' %><%= f.text_field :position %></div>
      <div><%= f.label :name, 'Desired Group size:' %><%= f.select :size, ['1-5 persons', '6-10 persons', '11-50 persons', '50-100 persons', '100-200 persons', 'More than 200 persons' ]%></div>
      <div><%= f.label :name, 'Group Tag:' %><%= f.select :category, ['Sports', 'Music', 'Entertainment', 'NBA' ]%></div>
      <div><%= f.label :visibility, 'Group Visibility:' %></div>
      <br>
      <div><%= f.label :visibility, 'Public To Everyone'%><%= f.radio_button :visibility, 'PublicToEveryone' %></div>
      <div><%= f.label :visibility, 'Private To Everyone' %><%= f.radio_button :visibility, 'PrivateToEveryone' %></div>
      <div><%= f.label :visibility, 'Public To Selected Friends' %><%= f.radio_button :visibility, 'PublicToSelectedFriends' %></div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.haml
#chatroom-page-container
  #chatroom-placeholder
    #left-div
      = link_to 'Explore Chatroom', chatrooms_path
    #right-div
      = link_to 'Create Chatroom', new_chatroom_path
  = render 'filter'

app/views/chatrooms/index.js.erb
$(document).ready(
	function() {
		if ($('#chatroom-page-container').find('.createchatroom').length !== 0) {
			$('#chatroom-page-container').find('.createchatroom').remove();
			$('#chatroom-page-container').find('#chatroom-filter').remove();
		}
		if ($('#chatroom-page-container').find('.showchatroom').length !== 0 ) {
		}
		else {
			$("<%= escape_javascript(render 'filter') %>").appendTo('#chatroom-page-container');
			var appenddiv = $('<div></div>');
			var appendh = $('<h1>All Groups</h1>');
			$('#chatroom-page-container').append(appendh);
			$('#chatroom-page-container').append(appenddiv);
			$('#chatroom-page-container').find('h1').addClass("chatroomheader");
			$('#chatroom-page-container').find('div').last().addClass("showchatroom");
			<% @chatrooms.each do |chatroom| %>
				$('.showchatroom').append("<p>" + "<%= j link_to chatroom.name, chatroom_chatroom_users_path(chatroom), :method => :post, :id => chatroom.id%>" + "</p>");
				$('.showchatroom').find("#<%= chatroom.id %>").append("<span>" + " <%= chatroom.users.length %>" + " users chatting in this room</span>");
				$('.showchatroom').find("#<%= chatroom.id %>").find('span').last().addClass("tailspan");
			<% end %>
			$('.showchatroom p').mouseover(function() {
				$(this).find('a').prepend("<span>Join Now</span>");
				$(this).find('span').first().addClass("middlespan");
			});

			$('.showchatroom p').mouseout(function() {
				$(this).find('a').find('.middlespan').remove();
			});
		}
	}
);

app/views/chatrooms/new.html.erb
<div id = "chatroom-page-container">
	<div id = "chatroom-placeholder">
    	<div id = "left-div">
      		<%= link_to 'Explore Chatroom', chatrooms_path %>
    	</div>
    	<div id = "right-div">
      		<%= link_to 'Create Chatroom', new_chatroom_path %>
    	</div>
    </div>
	<div class = 'createchatroom'>
		<%= render 'form' %>
	</div>
<div>

app/views/chatrooms/new.js.erb
$(document).ready(
	function() {
		if ($('#chatroom-page-container').find('.showchatroom').length !== 0 ) {
			$('#chatroom-page-container').find('.showchatroom').remove();
			$('#chatroom-page-container').find('.chatroomheader').remove();
			$('#chatroom-page-container').find('#chatroom-filter').remove();
		}
		if ($('#chatroom-page-container').find('.createchatroom').length !== 0 ) {
		}
		else{
			// $('#chatroom-page-container').find('#chatroom-filter').remove();
			$('#chatroom-page-container').append("<div></div>");
			$('#chatroom-page-container').find('div').last().addClass('createchatroom');
			$("<%= escape_javascript(render 'form') %>").appendTo('.createchatroom');
		}
	}
);

app/views/chatrooms/show.html.erb
<div id = "channel-main-container">
  <div id = "left-container">
    <div id = "group-container">
      <h1>My Group</h1>
      <% current_user.chatrooms.each do |chatroom|%>
        <p><%= link_to chatroom.name, chatroom_path(chatroom)%>
      <% end %>
    </div>
    <div id = "post-container">
      <%= link_to chatroom_chatroomposts_path(params[:id]) do %>
        <p><i class="fa fa-plus" aria-hidden="true"></i>New Post</p>
      <% end %>
    </div>
  </div>

  <div id = "right-container">
    <p>
      <%= @chatroom.name %>
    </p>
    <%= content_tag :div, :id => "message-board", 'data-value' => @chatroom.id do %>
	    <% @chatroom.messages.each do |message| %>
	      <div class = "every-post"><strong><%= message.user.username %> : </strong><%= sanitize message.body%></div>
	    <% end %>
    <% end %>

    <div id = "new-message">
      <%= form_for [@chatroom, Message.new], remote: true do |f| %>
        <div id = "message-input">
          <%= f.text_field :body %>
        </div>
        <div id = "chatroom-submit">
          <%= f.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>