config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :chatrooms
  root "firstpages#index"
  resources :forums
  resources :users, only: [:index, :create]
  resources :sessions, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :homes, only: [:index, :create, :new]
  scope '/homes' do
    resources :profiles, only: [:index, :create]
  end
  get '/forumsearch', to: "forums#search", as: 'search_forum'
  resources :firstpages
  resources :chatrooms do
    resources :chatroom_users
    resources :messages
    resources :chatroomposts
  end

  post '/createintro/:id', to: "homes#createupdateintro", as: "create_intro"

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
	has_many :chatroom_users
	has_many :users, through: :chatroom_users
	has_many :messages
	has_many :chatroomposts
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/chatroompost.rb
class Chatroompost < ApplicationRecord
	belongs_to :chatroom

	def self.find_post_author_img(post)
		User.find_by_username(post.author).image_url(:thumb)
	end
end

app/models/forum.rb
class Forum < ApplicationRecord
    def self.filter_by_college_name(arg)
      record = Forum.where('name LIKE ?', '%'+ arg.strip+ '%').all
    end
end

app/models/interest.rb
class Interest < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    # attr_accessible :image
    has_many :chatroom_users
    has_many :messages 
    has_many :chatrooms, through: :chatroom_users
    attr_accessor :password 
    before_create :encrypt_password
    validates_uniqueness_of :username, :email
    validates_confirmation_of :password
    validates_presence_of :password, :username, :email, :password_confirmation, :on => :create
    require 'carrierwave/orm/activerecord'
    mount_uploader :image, UserimageUploader
    mount_uploader :background, UserimageUploader
    def encrypt_password
        self.passwordsalt = BCrypt::Engine.generate_salt
        self.encrypted_password = BCrypt::Engine.hash_secret(password, self.passwordsalt)
    end
    
    def self.authenticate(user, password)
        if user.encrypted_password != BCrypt::Engine.hash_secret(password, user.passwordsalt)  
          return false
        else
          return true
        end
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
    before_action :find_forum, only: [:show, :destroy]
    
    def create
        @forum = Forum.new(forum_params)
        if @forum.save
            redirect_to forum_path(@forum.id)
        else
            render "create"
        end
    end
    
    def index
        @user = current_user
        @forum = Forum.new
        respond_to do |format|
            format.html
        end
    end
    
    def search
        @user = current_user
        if params[:content]
          puts "params is"
          puts params[:content]
          @course = Forum.filter_by_college_name(params[:content])
          puts "hehehehe"
          puts @course
          respond_to do |format|
            format.html
            format.json {render json: @course}
          end
        end
    end
    
    def show
        @name = @forum.name
        @coursename = @forum.coursename
    end
    
    def destroy
    
    end
    
    private
    def forum_params
        params.require(:forum).permit(:name, :coursename)
    end
    
    def find_forum
        @forum = Forum.find(params[:id])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :check_login
    def check_login
        redirect_to root_path if !current_user
    end
    def index
        @user = current_user
    end
    
    
    # call this create method to create user selfie and user background image 
    def create
        if user_params[:image]
          current_user.update(:image => user_params[:image])
        elsif user_params[:background]
          current_user.update(:background => user_params[:background])
        end
        redirect_to action: "index"
    end
    
    def new
        puts("go to this method")
        @user = current_user
        respond_to do |format|
            format.js{puts "hehehehehehehe"}
        end
    end

    # an action of creating or updating the personal intro
    def createupdateintro
        current_user.update(:introduction => user_params[:introduction])
        redirect_to homes_path
    end
    
    private
    def user_params
      params.require(:user).permit(:image, :background, :introduction)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
   before_action :set_chatroom

   def create
      puts "the text message is"
      message_params[:body] = message_params[:body].strip
      puts message_params[:body]
   	@message = @chatroom.messages.new(message_params)
   	@message.user = current_user
   	@message.save
   	respond_to do |format|
   	  format.js{MessageRelayJob.perform_later(@message)}
   	  format.html {redirect_to @chatroom}
   	end
   end


   private
   def set_chatroom
   	 @chatroom = Chatroom.find(params[:chatroom_id])
   end

   def message_params
   	 params.require(:message).permit(:body)
   end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def index
        @user = current_user
    end
    
    def create
    end
    
    
    
    private
    def user_params
      params.require(:user).permit(:image, :background, :name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :check_login, only: [:index, :create]
    
    def check_login
        redirect_to homes_path if current_user
    end
    
    def index
        respond_to do |format|
            format.html{redirect_to root_path}
            format.js{}
        end
    end
    
    
    
    def create
        user = User.find_by_username(user_params[:username])
        if !user
            @loginerror = "The Username doesn't exist"
            puts "enter here no user"
            respond_to do |format|
                puts "here too!"
                format.js{}
            end
        elsif !User.authenticate(user, user_params[:password])
            @loginerror = "The Username doesn't match with the password"
            puts "enter here not match"
            respond_to do |format|
                format.js{}
            end
        else
            @loginerror = ""
            puts "enter here everything is correct"
            session[:user_id] = user.id
            render :js => "window.location = '#{homes_path}'"
        end
    end
    
    def destroy
       session[:user_id] = nil
       redirect_to action: "index"
    end
    
    
    
    private
      def user_params
          params.permit(:username, :password)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login
  def check_login
    redirect_to homes_path if current_user
  end
  
  def index
    @user = User.new
    respond_to do |format|
      format.js {}
      format.html {redirect_to root_path}
    end
  end

  
  def create
    @new_user = User.new(user_params)
    if @new_user.save
      session[:user_id] = @new_user.id
      render :js => "window.location = '#{homes_path}'"
    else
      flash[:errors] = @new_user.errors.full_messages
      @signuperror = flash[:errors][0]
      respond_to do |format|
        format.js{}
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroomposts_helper.rb
module ChatroompostsHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
    
end

app/helpers/interest_helper.rb
module InterestHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def display_login_error
        if flash[:loginerror]
          content_tag(:p, flash[:loginerror])
        end
    end
end

app/views/homes/_introduction.html.haml
= form_for @user, :url => create_intro_path(@user), :method => "post" do |f|
    = f.text_area :introduction, :placeholder => "Write something about yourself", :id => "introduction-field"
    = f.submit "Submit", :id => "introduction-button"

app/views/homes/_navigation.html.haml
#background-container
  - unless current_user.background.blank?
    = image_tag src = current_user.background_url(:arm), :id => "background"
  - else
    = image_tag src = "http://wallpapercave.com/wp/L0a8ton.jpg", :id => "background"
  #background-slogan
    %p#title
      Bubbles
    %p#slogan
      Explore and find the community you will dedicate to 
  #image-frame
    - unless current_user.image.blank?
      #image-container
        = image_tag src = current_user.image_url(:thumb), :id => "selfie"
    - else
      #image-container
        = image_tag src = asset_path("user-image.png"), :id => "selfie"
    #image-cammera
      %i.fa.fa-camera#selfie-camera
#sub-navbar
.introduction-title
  %h1
    About Me (
    = current_user.username
    )  
    = link_to ("<i class='fa fa-pencil-square-o' aria-hidden='true'></i>").html_safe, new_home_path, :remote => true, :class => "link_to_group"

#self-introduction
  %p
    - if current_user.introduction
      = current_user.introduction
    - else
      Give a brief introduction about yourself.

#my-group
  .introduction-title
    %h1
      My Group
      = link_to ("<i class='fa fa-plus' aria-hidden='true'></i>/<i class='fa fa-universal-access' aria-hidden='true'></i>").html_safe, chatrooms_path, :class => "link_to_group"
  - if current_user.chatrooms.empty?
    %p
      You haven't joined any group yet.
  - else
    #all-my-group
      - current_user.chatrooms.each do |chatroom|
        = link_to chatroom_path(chatroom) do
          .each-group
            .each-group-img
              = image_tag src = "http://all4desktop.com/data_images/original/4246314-bubble.jpg"
            .each-group-name
              = chatroom.name

%footer
  .introduction-title
    %h1
      About Us Information


%div.modal#add
  %div.modal-container
    %h2 Image Upload
    = link_to ("<i class='fa fa-times' aria-hidden='true'></i>").html_safe, homes_path, :id => "close-selfie-upload"
    #photo-form-div
      = form_for @user, :url => homes_path(@user), :method => :post do |f|
        %label.custom-file-upload
          %i.fa.fa-upload
          Upload Image
          = f.file_field :image, :id => "file"
        %p
          = button_tag do 
            <i class='fa fa-floppy-o' aria-hidden='true'></i> Save Image
          / = f.submit ("<i class='fa fa-floppy-o' aria-hidden='true'></i>Save Image").html_safe, :id => "save-button"
    = link_to "close", "#", :id => "close-link"

app/views/homes/index.html.haml
= render "navigation"

app/views/homes/new.js.erb
$('#self-introduction').html("")
$("<%= escape_javascript(render '/homes/introduction') %>").appendTo('#self-introduction');

app/views/profiles/_basicinfo.html.haml
= form_for @user, :url => profiles_path(@user), :method => :post do |f|
  %p
    = f.label :真实姓名
    = f.text_field :name, :id => "name"
  %p
    = f.submit "保存", :id => "save-button"

app/views/profiles/index.html.haml
= render 'homes/navigation'
%div.profile-container.header
  %h2 大学
%div.profile-container.body
  #profile-left
    %ul
      %li.profile-li
        基本信息
      %li.profile-li
        个人爱好
      %li.profile-li
        工作/活动经历
  #profile-right
    #div1
      = render 'basicinfo'
    #div2
      2222222
    #div3
      3333333
    